'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("rylCoder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;!-- 
        '''################################################
        '''##                                            ##
        '''##         RYL mcf &amp; gsf file editor          ##
        '''##                                            ##
        '''##   (C) 2006 &amp; 2007 AlphA                    ##
        '''##                                            ##
        '''##   This source is for private development.  ##
        '''##   You can have this source only with the   ##
        '''##   owners permission.                       ##
        '''##             [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gsfStruct() As String
            Get
                Return ResourceManager.GetString("gsfStruct", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property npcShopBg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npcShopBg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property npcShopNotFound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npcShopNotFound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property showOnMapSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showOnMapSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property X_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Xa_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xa_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;syntax&gt;
        '''  &lt;ryl version=&quot;2&quot;&gt;
        '''    &lt;mcf type=&quot;1&quot;&gt;
        '''      &lt;!-- NPCscript.mcf --&gt;
        '''      &lt;func name=&quot;AddItem&quot; parcount=&quot;5&quot; desc=&quot;Add a new item to NPC shop&quot;&gt;
        '''        &lt;param type=&quot;int&quot; name=&quot;NPC id&quot; desc=&quot;The NPC ID to who&apos;s shop to add current item&quot; /&gt;
        '''        &lt;param type=&quot;int&quot; name=&quot;Shop&quot; desc=&quot;If the NPC has multiple shops then each shop has its id starting from 0. Default is 0. Reference to AddPopup();&quot; /&gt;
        '''        &lt;param type=&quot;int&quot; name=&quot;Tab&quot; desc=&quot;Tab ID. From 0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property xmlFunctionSyntax() As String
            Get
                Return ResourceManager.GetString("xmlFunctionSyntax", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property zone_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zone_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zone_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
